export const AUDIT_MODULE_OPTIONS = [
  ["PROCUREMENT", "Procurement"],
  ["EXPENSES", "Expenses"],
  ["CONTRACTORS", "Contractors"],
  ["SECURITY", "Security"],
  ["USERS", "Users / Staff"],
  ["ROLES", "Roles / Permissions"],
  ["RESTAURANT", "Restaurant"],
  ["BRANCHES", "Branches"],
  ["MENU", "Menu"],
  ["TABLES", "Tables"],
  ["RESERVATIONS", "Reservations"],
  ["INVENTORY", "Inventory"],
  ["PAYROLL", "Payroll"],
  ["ATTENDANCE", "Attendance"],
  ["KITCHEN_CONFIG", "Kitchen Configuration"],
  ["REPORTS", "Reports"],
  ["SETTINGS", "Settings"],
  ["MIGRATIONS", "Migrations / Transfers"],
];

export const AUDIT_ACTION_OPTIONS = [
  ["CREATE", "Create"],
  ["UPDATE", "Update"],
  ["DELETE", "Delete"],
  ["APPROVE", "Approve"],
  ["REJECT", "Reject"],
  ["CANCEL", "Cancel"],
  ["RESTORE", "Restore"],
  ["PAYMENT", "Payment"],
  ["STATUS_CHANGE", "Status change"],
  ["ASSIGNMENT_CHANGE", "Assignment change"],
  ["CONFIG_CHANGE", "Config change"],
  ["EXPORT", "Export"],
  ["LOGIN_SUCCESS", "Login success"],
  ["LOGIN_FAILED", "Login failed"],
  ["MIGRATION", "Migration"],
];
