# Generated by Django 5.2 on 2026-04-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_restaurant_table_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
