# Generated by Django 5.2 on 2026-04-21 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_table_number'),
        ('restaurants', '0003_restaurant_delivery_available_restaurant_facebook_and_more'),
        ('users', '0015_rename_restaurant_attendance_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='allow_free_reservation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='table',
            name='reservation_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('guests', models.PositiveIntegerField(default=1)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('reservation_type', models.CharField(choices=[('free', 'Free'), ('fee', 'Reservation Fee'), ('prepaid', 'Prepaid')], default='free', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='reserved', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.staff')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurants.restaurant')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='orders.table')),
            ],
        ),
    ]
