# Generated by Django 5.2 on 2026-04-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_reservation_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='number',
        ),
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
