# Generated by Django 5.2 on 2026-04-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customer_restaurant'),
        ('orders', '0030_order_is_printed'),
        ('restaurants', '0005_restaurant_base_delivery_fee_restaurant_price_per_km'),
        ('users', '0016_alter_staff_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('restaurant', 'order_number'), name='unique_order_number_per_restaurant'),
        ),
    ]
