# Generated by Django 5.2 on 2026-05-13 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_platter_platteritem'),
        ('orders', '0032_order_discount_amount_order_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='platter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.platter'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem'),
        ),
    ]
