# Generated by Django 5.2 on 2026-05-15 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_orderitem_platter_alter_orderitem_menu_item'),
        ('users', '0017_alter_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_order_items', to='users.staff'),
        ),
    ]
