# Generated by Django 5.2 on 2026-05-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_orderitem_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_prepared',
            field=models.BooleanField(default=False),
        ),
    ]
