# Generated by Django 5.2 on 2026-05-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_orderitem_is_prepared'),
        ('restaurants', '0007_restaurant_admin_discount_limit_and_more'),
        ('users', '0017_alter_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('restaurant', 'reservation_number'), name='unique_reservation_number_per_restaurant'),
        ),
    ]
