# Generated by Django 5.2 on 2026-05-21 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_orderitem_approved_at_orderitem_cancelled_at_and_more'),
        ('users', '0017_alter_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_items', to='users.staff'),
        ),
    ]
