# Generated by Django 5.2 on 2026-05-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_orderitem_cancelled_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_prepared',
        ),
    ]
