# Generated by Django 5.2 on 2026-06-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_printed_to_kitchen',
            field=models.BooleanField(default=False),
        ),
    ]
