# Generated by Django 5.2 on 2026-06-03 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_discountcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.discountcard'),
        ),
    ]
