# Generated by Django 5.2 on 2026-06-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_order_discount_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_at_order',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price of the item/platter when this order was placed', max_digits=8, null=True),
        ),
    ]
