# Generated by Django 5.2 on 2026-07-28 09:41

import django.db.models.deletion
from django.db import migrations, models


def assign_main_branch(apps, schema_editor):
    Branch = apps.get_model("restaurants", "Branch")
    for model_name in ["DiscountCard", "Order", "Reservation", "Table"]:
        Model = apps.get_model("orders", model_name)
        for obj in Model.objects.filter(restaurant__isnull=False, branch__isnull=True):
            branch = Branch.objects.filter(
                restaurant_id=obj.restaurant_id,
                is_main_branch=True,
            ).first()
            if branch:
                Model.objects.filter(pk=obj.pk).update(branch=branch)


def clear_branch(apps, schema_editor):
    for model_name in ["DiscountCard", "Order", "Reservation", "Table"]:
        Model = apps.get_model("orders", model_name)
        Model.objects.update(branch=None)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_auto_20260610_0528'),
        ('restaurants', '0009_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcard',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_cards', to='restaurants.branch'),
        ),
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurants.branch'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurants.branch'),
        ),
        migrations.AddField(
            model_name='table',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.branch'),
        ),
        migrations.RunPython(assign_main_branch, clear_branch),
    ]
