# Generated by Django 5.2 on 2026-04-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_table_allow_free_reservation_table_reservation_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='reservation_price',
            new_name='price_per_hour',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
