# Generated by Django 5.2 on 2026-04-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_order_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
