# Generated by Django 5.2 on 2026-04-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_remove_order_waiter_order_created_by_order_paid_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paid_by',
            new_name='received_by',
        ),
    ]
