# Generated by Django 5.2 on 2026-04-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_alter_reservation_created_by_alter_reservation_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='reserved', max_length=20),
        ),
    ]
