# Generated by Django 5.2 on 2026-05-13 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_category_restaurant_menuitem_restaurant_and_more'),
        ('restaurants', '0006_restaurant_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='platters/')),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platters', to='menu.category')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platters', to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='PlatterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platter_items', to='menu.menuitem')),
                ('platter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.platter')),
            ],
        ),
    ]
