# Generated by Django 5.2 on 2026-05-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_platter_platteritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_manually_available',
            field=models.BooleanField(default=True),
        ),
    ]
