# Generated by Django 5.2 on 2026-05-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_menuitem_is_manually_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='platter',
            name='is_manually_available',
            field=models.BooleanField(default=True),
        ),
    ]
