# Generated by Django 5.2 on 2026-06-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_platter_is_manually_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_dari',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_pashto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_dari',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_pashto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_dari',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_pashto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='platter',
            name='description_dari',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platter',
            name='description_pashto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platter',
            name='name_dari',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='platter',
            name='name_pashto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
