# Generated by Django 5.2 on 2026-06-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_category_image'),
        ('restaurants', '0008_restaurant_slogan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['rank']},
        ),
        migrations.AddField(
            model_name='category',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('restaurant', 'rank'), name='unique_rank_per_restaurant'),
        ),
    ]
