# Generated by Django 5.2 on 2026-06-23 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_alter_category_options_category_rank_and_more'),
        ('restaurants', '0008_restaurant_slogan'),
        ('users', '0018_alter_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='uses_daily_production',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_produced', models.PositiveIntegerField(help_text='Total portions cooked in this batch')),
                ('quantity_remaining', models.PositiveIntegerField(help_text='Portions still available to sell')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.staff')),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production', to='menu.menuitem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
