# Generated by Django 5.2 on 2026-07-28 09:41

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def assign_branches(apps, schema_editor):
    Branch = apps.get_model("restaurants", "Branch")
    Production = apps.get_model("menu", "Production")
    Review = apps.get_model("menu", "Review")
    Staff = apps.get_model("users", "Staff")
    Order = apps.get_model("orders", "Order")

    main_branch = Branch.objects.filter(
        restaurant_id=OuterRef("restaurant_id"),
        is_main_branch=True,
    ).values("id")[:1]
    staff_active_branch = Staff.objects.filter(
        pk=OuterRef("created_by_id"),
    ).values("active_branch_id")[:1]
    delivery_branch = Order.objects.filter(
        pk=OuterRef("delivery_id"),
    ).values("branch_id")[:1]

    Production.objects.filter(
        restaurant_id__isnull=False,
        branch_id__isnull=True,
        created_by_id__isnull=False,
    ).update(branch_id=Subquery(staff_active_branch))

    Production.objects.filter(
        restaurant_id__isnull=False,
        branch_id__isnull=True,
    ).update(branch_id=Subquery(main_branch))

    Review.objects.filter(
        restaurant_id__isnull=False,
        branch_id__isnull=True,
        delivery_id__isnull=False,
    ).update(branch_id=Subquery(delivery_branch))

    Review.objects.filter(
        restaurant_id__isnull=False,
        branch_id__isnull=True,
    ).update(branch_id=Subquery(main_branch))


def clear_branch(apps, schema_editor):
    apps.get_model("menu", "Production").objects.update(branch=None)
    apps.get_model("menu", "Review").objects.update(branch=None)


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_menuitem_uses_daily_production_production'),
        ('orders', '0046_discountcard_branch_order_branch_reservation_branch_and_more'),
        ('restaurants', '0009_branch'),
        ('users', '0020_staff_branches_active_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='restaurants.branch'),
        ),
        migrations.AddField(
            model_name='review',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurants.branch'),
        ),
        migrations.RunPython(assign_branches, clear_branch),
    ]
