# Generated by Django 5.2 on 2026-07-28 09:41

import django.db.models.deletion
from django.db import migrations, models


def assign_branches(apps, schema_editor):
    Branch = apps.get_model("restaurants", "Branch")
    Production = apps.get_model("menu", "Production")
    Review = apps.get_model("menu", "Review")

    for production in Production.objects.filter(
        restaurant__isnull=False,
        branch__isnull=True,
    ).select_related("created_by"):
        branch = getattr(production.created_by, "active_branch", None)
        if not branch:
            branch = Branch.objects.filter(
                restaurant_id=production.restaurant_id,
                is_main_branch=True,
            ).first()
        if branch:
            Production.objects.filter(pk=production.pk).update(branch=branch)

    for review in Review.objects.filter(
        restaurant__isnull=False,
        branch__isnull=True,
    ).select_related("delivery"):
        branch = getattr(review.delivery, "branch", None)
        if not branch:
            branch = Branch.objects.filter(
                restaurant_id=review.restaurant_id,
                is_main_branch=True,
            ).first()
        if branch:
            Review.objects.filter(pk=review.pk).update(branch=branch)


def clear_branch(apps, schema_editor):
    apps.get_model("menu", "Production").objects.update(branch=None)
    apps.get_model("menu", "Review").objects.update(branch=None)


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_menuitem_uses_daily_production_production'),
        ('orders', '0046_discountcard_branch_order_branch_reservation_branch_and_more'),
        ('restaurants', '0009_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='restaurants.branch'),
        ),
        migrations.AddField(
            model_name='review',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurants.branch'),
        ),
        migrations.RunPython(assign_branches, clear_branch),
    ]
