# Generated by Django 5.2 on 2026-08-07 10:38

from django.core.exceptions import FieldDoesNotExist
import django.db.models.deletion
from django.db import migrations, models


MAIN_KITCHEN_NAME = "Main Kitchen"


def has_foreign_key(model, field_name):
    """
    Returns True if the historical model has a ForeignKey field
    with the expected '<field>_id' attribute.
    """
    try:
        field = model._meta.get_field(field_name)
    except FieldDoesNotExist:
        return False

    return (
        not getattr(field, "many_to_many", False)
        and getattr(field, "attname", None) == f"{field_name}_id"
    )


def has_many_to_many(model, field_name):
    try:
        field = model._meta.get_field(field_name)
    except FieldDoesNotExist:
        return False

    return getattr(field, "many_to_many", False)


def get_or_create_main_kitchen(Station, restaurant_id, branch_id=None):
    """
    Creates a Main Kitchen for a restaurant/branch combination.

    branch_id=None means the station applies to the entire restaurant.
    """
    station, created = Station.objects.get_or_create(
        restaurant_id=restaurant_id,
        branch_id=branch_id,
        name=MAIN_KITCHEN_NAME,
        defaults={
            "name_dari": "آشپزخانه عمومی",
            "name_pashto": "عمومي پخلنځی",
            "description": "Default Main Kitchen Station",
            "is_default": True,
            "is_active": True,
        },
    )

    # Make sure an existing Main Kitchen is marked as default and active.
    fields_to_update = []

    if not station.is_default:
        station.is_default = True
        fields_to_update.append("is_default")

    if not station.is_active:
        station.is_active = True
        fields_to_update.append("is_active")

    if fields_to_update:
        station.save(update_fields=fields_to_update)

    return station


def assign_items_to_stations(
    ItemModel,
    restaurant_id,
    restaurant_station,
    branch_stations,
):
    """
    Assigns existing MenuItems or Platters to Main Kitchen stations.

    If the model has a branch ForeignKey:
        - branch-specific items go to their branch Main Kitchen
        - items without a branch go to the restaurant-wide Main Kitchen

    If the model does not have a branch field:
        - all items go to the restaurant-wide Main Kitchen
    """
    items = ItemModel.objects.filter(
        restaurant_id=restaurant_id,
        station__isnull=True,
    )

    if not has_foreign_key(ItemModel, "branch"):
        items.update(station_id=restaurant_station.pk)
        return

    # Items without a branch belong to the restaurant-wide station.
    items.filter(branch_id__isnull=True).update(
        station_id=restaurant_station.pk
    )

    # Branch-specific items belong to the matching branch station.
    for branch_id, branch_station in branch_stations.items():
        items.filter(branch_id=branch_id).update(
            station_id=branch_station.pk
        )

    # Any remaining items with an invalid/missing branch are assigned
    # to the restaurant-wide Main Kitchen so no existing item is left
    # without a station.
    items.filter(station__isnull=True).update(
        station_id=restaurant_station.pk
    )


def create_default_stations_and_assign_data(apps, schema_editor):
    Restaurant = apps.get_model("restaurants", "Restaurant")
    Branch = apps.get_model("restaurants", "Branch")
    Station = apps.get_model("menu", "Station")
    MenuItem = apps.get_model("menu", "MenuItem")
    Platter = apps.get_model("menu", "Platter")

    restaurant_stations = {}

    # Create stations for every existing restaurant.
    for restaurant_id in Restaurant.objects.values_list(
        "pk",
        flat=True,
    ).iterator():

        # Restaurant-wide Main Kitchen.
        restaurant_station = get_or_create_main_kitchen(
            Station=Station,
            restaurant_id=restaurant_id,
            branch_id=None,
        )

        branch_stations = {}

        # Branch-specific Main Kitchens.
        branch_ids = Branch.objects.filter(
            restaurant_id=restaurant_id,
        ).values_list("pk", flat=True)

        for branch_id in branch_ids.iterator():
            branch_stations[branch_id] = get_or_create_main_kitchen(
                Station=Station,
                restaurant_id=restaurant_id,
                branch_id=branch_id,
            )

        restaurant_stations[restaurant_id] = (
            restaurant_station,
            branch_stations,
        )

    # Assign existing MenuItems and Platters.
    for restaurant_id, (
        restaurant_station,
        branch_stations,
    ) in restaurant_stations.items():

        assign_items_to_stations(
            ItemModel=MenuItem,
            restaurant_id=restaurant_id,
            restaurant_station=restaurant_station,
            branch_stations=branch_stations,
        )

        assign_items_to_stations(
            ItemModel=Platter,
            restaurant_id=restaurant_id,
            restaurant_station=restaurant_station,
            branch_stations=branch_stations,
        )

   


def reverse_default_stations(apps, schema_editor):
    Station = apps.get_model("menu", "Station")
    MenuItem = apps.get_model("menu", "MenuItem")
    Platter = apps.get_model("menu", "Platter")

    station_ids = list(
        Station.objects.filter(
            name=MAIN_KITCHEN_NAME,
            is_default=True,
        ).values_list("pk", flat=True)
    )

    if not station_ids:
        return

    # Clear station references before deleting the stations.
    MenuItem.objects.filter(
        station_id__in=station_ids,
    ).update(station_id=None)

    Platter.objects.filter(
        station_id__in=station_ids,
    ).update(station_id=None)

    # Staff ManyToMany records are automatically removed when
    # the related Station records are deleted.
    Station.objects.filter(pk__in=station_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "menu",
            "0019_remove_branch_menu_overrides",
        ),
        (
            "restaurants",
            "0016_subscription_max_branches",
        ),

        # Change this to the latest users migration that exists
        # before the Staff.stations field is added.
        #
        # For example:
        # ("users", "0014_alter_staff_branches"),
        #\
       
    ]

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100),
                ),
                (
                    "name_dari",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "name_pashto",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "True if this is the default station "
                            "(Main Kitchen) for the restaurant."
                        ),
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            "Optional: If null, the station applies "
                            "to all branches of the restaurant."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stations",
                        to="restaurants.branch",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stations",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "name"],
                "indexes": [
                    models.Index(
                        fields=["restaurant", "is_active"],
                        name="station_rest_act_idx",
                    ),
                    models.Index(
                        fields=["restaurant", "is_default"],
                        name="station_rest_def_idx",
                    ),
                ],
                "unique_together": {
                    ("restaurant", "name", "branch"),
                },
            },
        ),

        migrations.AddField(
            model_name="menuitem",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="menu_items",
                to="menu.station",
            ),
        ),

        migrations.AddField(
            model_name="platter",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="platters",
                to="menu.station",
            ),
        ),

        

        migrations.RunPython(
            create_default_stations_and_assign_data,
            reverse_default_stations,
        ),
    ]