# Generated by Django 5.2 on 2026-08-07 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='station',
            field=models.ForeignKey(blank=True, help_text='The kitchen station responsible for preparing this item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='menu.station'),
        ),
        migrations.AlterField(
            model_name='platter',
            name='station',
            field=models.ForeignKey(blank=True, help_text='The kitchen station responsible for preparing this platter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platters', to='menu.station'),
        ),
    ]
