# Generated by Django 5.2 on 2026-08-09 00:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_alter_menuitem_station_alter_platter_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platteritem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Quantity of the menu item included in this platter (supports fractional amounts like 0.5 or 0.2).', max_digits=8),
        ),
    ]
