# Generated by Django 5.2 on 2026-06-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expenses_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensehistory',
            name='amount_afn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expensehistory',
            name='currency',
            field=models.CharField(choices=[('AFN', 'Afghani'), ('USD', 'US Dollar')], default='AFN', max_length=3),
        ),
        migrations.AddField(
            model_name='expensehistory',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='expenses',
            name='amount_afn',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenses',
            name='currency',
            field=models.CharField(choices=[('AFN', 'Afghani'), ('USD', 'US Dollar')], default='AFN', max_length=3),
        ),
        migrations.AddField(
            model_name='expenses',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=1, help_text='1 USD = ? AFN', max_digits=10),
        ),
        migrations.AlterField(
            model_name='expensehistory',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], default='created', max_length=10),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Original amount entered by user', max_digits=10),
        ),
    ]
