# Generated by Django 5.2 on 2026-07-28 09:41

import django.db.models.deletion
from django.db import migrations, models


def assign_main_branch(apps, schema_editor):
    Branch = apps.get_model("restaurants", "Branch")
    for model_name in ["ExpenseHistory", "Expenses"]:
        Model = apps.get_model("expenses", model_name)
        for obj in Model.objects.filter(restaurant__isnull=False, branch__isnull=True):
            branch = Branch.objects.filter(
                restaurant_id=obj.restaurant_id,
                is_main_branch=True,
            ).first()
            if branch:
                Model.objects.filter(pk=obj.pk).update(branch=branch)


def clear_branch(apps, schema_editor):
    apps.get_model("expenses", "ExpenseHistory").objects.update(branch=None)
    apps.get_model("expenses", "Expenses").objects.update(branch=None)


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expensehistory_amount_afn_expensehistory_currency_and_more'),
        ('restaurants', '0009_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensehistory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_histories', to='restaurants.branch'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='restaurants.branch'),
        ),
        migrations.RunPython(assign_main_branch, clear_branch),
    ]
