# Generated by Django 5.2 on 2026-04-20 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_slug'),
        ('system', '0002_rename_resaurantinfo_restaurantinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantinfo',
            name='restaurant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
    ]
