# Generated by Django 5.2 on 2026-06-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_stockmovement_note_stockmovement_unit_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('order', 'Order'), ('adjustment', 'Adjustment'), ('waste', 'Waste'), ('production', 'Production'), ('production_adjustment', 'Production Adjustment')], max_length=30),
        ),
    ]
