# Generated by Django 5.2 on 2026-07-28 09:41

import django.db.models.deletion
from django.db import migrations, models


def assign_branches(apps, schema_editor):
    Branch = apps.get_model("restaurants", "Branch")
    Ingredient = apps.get_model("inventory", "Ingredient")
    StockMovement = apps.get_model("inventory", "StockMovement")

    for ingredient in Ingredient.objects.filter(
        restaurant__isnull=False,
        branch__isnull=True,
    ):
        branch = Branch.objects.filter(
            restaurant_id=ingredient.restaurant_id,
            is_main_branch=True,
        ).first()
        if branch:
            Ingredient.objects.filter(pk=ingredient.pk).update(branch=branch)

    for movement in StockMovement.objects.filter(
        restaurant__isnull=False,
        branch__isnull=True,
    ).select_related("related_order", "ingredient"):
        branch = None
        if movement.related_order_id:
            branch = getattr(movement.related_order, "branch", None)
        if not branch and movement.ingredient_id:
            branch = getattr(movement.ingredient, "branch", None)
        if not branch:
            branch = Branch.objects.filter(
                restaurant_id=movement.restaurant_id,
                is_main_branch=True,
            ).first()
        if branch:
            StockMovement.objects.filter(pk=movement.pk).update(branch=branch)


def clear_branch(apps, schema_editor):
    apps.get_model("inventory", "StockMovement").objects.update(branch=None)
    apps.get_model("inventory", "Ingredient").objects.update(branch=None)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_stockmovement_movement_type'),
        ('orders', '0046_discountcard_branch_order_branch_reservation_branch_and_more'),
        ('restaurants', '0009_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='restaurants.branch'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='restaurants.branch'),
        ),
        migrations.RunPython(assign_branches, clear_branch),
    ]
