# Generated by Django 5.2 on 2026-07-28 09:41

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def assign_branches(apps, schema_editor):
    Branch = apps.get_model("restaurants", "Branch")
    Ingredient = apps.get_model("inventory", "Ingredient")
    StockMovement = apps.get_model("inventory", "StockMovement")
    Order = apps.get_model("orders", "Order")

    main_branch = Branch.objects.filter(
        restaurant_id=OuterRef("restaurant_id"),
        is_main_branch=True,
    ).values("id")[:1]

    Ingredient.objects.filter(
        restaurant_id__isnull=False,
        branch_id__isnull=True,
    ).update(branch_id=Subquery(main_branch))

    order_branch = Order.objects.filter(
        pk=OuterRef("related_order_id"),
    ).values("branch_id")[:1]
    ingredient_branch = Ingredient.objects.filter(
        pk=OuterRef("ingredient_id"),
    ).values("branch_id")[:1]

    StockMovement.objects.filter(
        restaurant_id__isnull=False,
        branch_id__isnull=True,
        related_order_id__isnull=False,
    ).update(branch_id=Subquery(order_branch))

    StockMovement.objects.filter(
        restaurant_id__isnull=False,
        branch_id__isnull=True,
        ingredient_id__isnull=False,
    ).update(branch_id=Subquery(ingredient_branch))

    StockMovement.objects.filter(
        restaurant_id__isnull=False,
        branch_id__isnull=True,
    ).update(branch_id=Subquery(main_branch))


def clear_branch(apps, schema_editor):
    apps.get_model("inventory", "StockMovement").objects.update(branch=None)
    apps.get_model("inventory", "Ingredient").objects.update(branch=None)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_stockmovement_movement_type'),
        ('orders', '0046_discountcard_branch_order_branch_reservation_branch_and_more'),
        ('restaurants', '0009_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='restaurants.branch'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='restaurants.branch'),
        ),
        migrations.RunPython(assign_branches, clear_branch),
    ]
