# Generated by Django 5.2 on 2026-04-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_otp_customer_phone_verified_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_verified',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
