# Generated by Django 5.2 on 2026-04-20 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('users', '0011_staff_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='staff',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'Super Admin'), ('Admin', 'Admin'), ('Cashier', 'Cashier'), ('Waiter', 'Waiter'), ('Kitchen_manager', 'Kitchen Manager'), ('DeliveryBoy', 'Delivery Boy'), ('Other', 'Other')], max_length=20),
        ),
    ]
