# Generated by Django 5.2 on 2026-04-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_shift_restaurant_staff_restaurant_alter_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
