# Generated by Django 5.2 on 2026-04-24 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_restaurant_attendance_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='users.shift'),
        ),
    ]
