# Generated by Django 5.2 on 2026-05-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_staff_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'Super Admin'), ('Admin', 'Admin'), ('Manager', 'Manager'), ('Cashier', 'Cashier'), ('Waiter', 'Waiter'), ('Kitchen_manager', 'Kitchen Manager'), ('DeliveryBoy', 'Delivery Boy'), ('Other', 'Other')], max_length=20),
        ),
    ]
