# Generated by Django 5.2 on 2026-07-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'Super Admin'), ('Admin', 'Admin'), ('Manager', 'Manager'), ('Cashier', 'Cashier'), ('Call_operator', 'Call Operator'), ('Waiter', 'Waiter'), ('Kitchen_manager', 'Kitchen Manager'), ('DeliveryBoy', 'Delivery Boy'), ('InventoryManager', 'Inventory Manager'), ('Other', 'Other')], max_length=20),
        ),
    ]
