# Generated by Django 5.2 on 2026-07-28 09:41

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def assign_branches(apps, schema_editor):
    Branch = apps.get_model("restaurants", "Branch")
    Shift = apps.get_model("users", "Shift")
    Attendance = apps.get_model("users", "Attendance")
    Payroll = apps.get_model("users", "Payroll")
    Staff = apps.get_model("users", "Staff")

    main_branch = Branch.objects.filter(
        restaurant_id=OuterRef("restaurant_id"),
        is_main_branch=True,
    ).values("id")[:1]
    staff_active_branch = Staff.objects.filter(
        pk=OuterRef("staff_id"),
    ).values("active_branch_id")[:1]

    Shift.objects.filter(
        restaurant_id__isnull=False,
        branch_id__isnull=True,
    ).update(branch_id=Subquery(main_branch))

    Attendance.objects.filter(
        restaurant_id__isnull=False,
        branch_id__isnull=True,
        staff_id__isnull=False,
    ).update(branch_id=Subquery(staff_active_branch))

    Attendance.objects.filter(
        restaurant_id__isnull=False,
        branch_id__isnull=True,
    ).update(branch_id=Subquery(main_branch))

    Payroll.objects.filter(
        restaurant_id__isnull=False,
        branch_id__isnull=True,
        staff_id__isnull=False,
    ).update(branch_id=Subquery(staff_active_branch))

    Payroll.objects.filter(
        restaurant_id__isnull=False,
        branch_id__isnull=True,
    ).update(branch_id=Subquery(main_branch))


def clear_branch(apps, schema_editor):
    apps.get_model("users", "Attendance").objects.update(branch=None)
    apps.get_model("users", "Payroll").objects.update(branch=None)
    apps.get_model("users", "Shift").objects.update(branch=None)


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_branch'),
        ('users', '0020_staff_branches_active_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='restaurants.branch'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='restaurants.branch'),
        ),
        migrations.AddField(
            model_name='shift',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='restaurants.branch'),
        ),
        migrations.RunPython(assign_branches, clear_branch),
    ]
