# Generated by Django 5.2 on 2026-07-28 09:41

import django.db.models.deletion
from django.db import migrations, models


def assign_branches(apps, schema_editor):
    Branch = apps.get_model("restaurants", "Branch")
    Shift = apps.get_model("users", "Shift")
    Attendance = apps.get_model("users", "Attendance")
    Payroll = apps.get_model("users", "Payroll")

    for shift in Shift.objects.filter(restaurant__isnull=False, branch__isnull=True):
        branch = Branch.objects.filter(
            restaurant_id=shift.restaurant_id,
            is_main_branch=True,
        ).first()
        if branch:
            Shift.objects.filter(pk=shift.pk).update(branch=branch)

    for attendance in Attendance.objects.filter(
        restaurant__isnull=False,
        branch__isnull=True,
    ).select_related("staff"):
        branch = getattr(attendance.staff, "active_branch", None)
        if not branch:
            branch = Branch.objects.filter(
                restaurant_id=attendance.restaurant_id,
                is_main_branch=True,
            ).first()
        if branch:
            Attendance.objects.filter(pk=attendance.pk).update(branch=branch)

    for payroll in Payroll.objects.filter(
        restaurant__isnull=False,
        branch__isnull=True,
    ).select_related("staff"):
        branch = getattr(payroll.staff, "active_branch", None)
        if not branch:
            branch = Branch.objects.filter(
                restaurant_id=payroll.restaurant_id,
                is_main_branch=True,
            ).first()
        if branch:
            Payroll.objects.filter(pk=payroll.pk).update(branch=branch)


def clear_branch(apps, schema_editor):
    apps.get_model("users", "Attendance").objects.update(branch=None)
    apps.get_model("users", "Payroll").objects.update(branch=None)
    apps.get_model("users", "Shift").objects.update(branch=None)


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_branch'),
        ('users', '0020_staff_branches_active_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='restaurants.branch'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='restaurants.branch'),
        ),
        migrations.AddField(
            model_name='shift',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='restaurants.branch'),
        ),
        migrations.RunPython(assign_branches, clear_branch),
    ]
