# Generated by Django 5.2 on 2026-08-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_station'),
        ('users', '0023_enterprise_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='stations',
            field=models.ManyToManyField(blank=True, help_text='Stations assigned to this kitchen manager.', related_name='assigned_staff', to='menu.station'),
        ),
    ]
