# Generated by Django 5.2 on 2026-08-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_staff_stations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'Super Admin'), ('Admin', 'Admin'), ('BranchAdmin', 'Branch Admin'), ('Manager', 'Manager'), ('FianceManager', 'Finance Manager'), ('OperationsManager', 'Operations Manager'), ('Cashier', 'Cashier'), ('Call_operator', 'Call Operator'), ('Waiter', 'Waiter'), ('Kitchen_manager', 'Kitchen Manager'), ('DeliveryBoy', 'Delivery Boy'), ('InventoryManager', 'Inventory Manager'), ('Other', 'Other')], max_length=20),
        ),
    ]
