# Generated by Django 5.2 on 2026-02-03 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='created_by',
        ),
    ]
