# Generated by Django 5.2 on 2026-02-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockmovement_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('adjustment', 'Adjustment'), ('waste', 'Waste')], max_length=20),
        ),
    ]
