# Generated by Django 5.2 on 2026-04-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockmovement_inventory_s_created_05ebf5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('order', 'Order'), ('adjustment', 'Adjustment'), ('waste', 'Waste')], max_length=20),
        ),
    ]
