# Generated by Django 5.2 on 2026-08-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('CANCEL', 'Cancel'), ('RESTORE', 'Restore'), ('PAYMENT', 'Payment'), ('STATUS_CHANGE', 'Status Change'), ('ASSIGNMENT_CHANGE', 'Assignment Change'), ('CONFIG_CHANGE', 'Configuration Change'), ('EXPORT', 'Export'), ('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('MIGRATION', 'Migration')], max_length=30),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(choices=[('PROCUREMENT', 'Procurement'), ('EXPENSES', 'Expenses'), ('CONTRACTORS', 'Contractors'), ('SECURITY', 'Security'), ('USERS', 'Users / Staff'), ('ROLES', 'Roles / Permissions'), ('RESTAURANT', 'Restaurant'), ('BRANCHES', 'Branches'), ('MENU', 'Menu'), ('TABLES', 'Table Management'), ('RESERVATIONS', 'Reservations'), ('INVENTORY', 'Inventory'), ('PAYROLL', 'Payroll'), ('ATTENDANCE', 'Attendance'), ('KITCHEN_CONFIG', 'Kitchen Configuration'), ('REPORTS', 'Reports'), ('SETTINGS', 'Settings'), ('MIGRATIONS', 'Migrations / Transfers')], max_length=40),
        ),
    ]
