# Generated by Django 5.2 on 2026-04-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_delete_otp_remove_customer_phone_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
