# Generated by Django 5.2 on 2026-04-20 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_phone_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone_verified',
        ),
    ]
