# Generated by Django 5.2 on 2026-06-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customer_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='restaurant',
        ),
    ]
