# Generated by Django 5.2 on 2026-07-28 09:41

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def assign_main_branch(apps, schema_editor):
    Branch = apps.get_model("restaurants", "Branch")
    Notification = apps.get_model("reports", "Notification")

    main_branch = Branch.objects.filter(
        restaurant_id=OuterRef("restaurant_id"),
        is_main_branch=True,
    ).values("id")[:1]

    Notification.objects.filter(
        restaurant_id__isnull=False,
        branch_id__isnull=True,
    ).update(branch_id=Subquery(main_branch))


def clear_branch(apps, schema_editor):
    apps.get_model("reports", "Notification").objects.update(branch=None)


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_notification_restaurant'),
        ('restaurants', '0009_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='restaurants.branch'),
        ),
        migrations.RunPython(assign_main_branch, clear_branch),
    ]
