# Generated by Django 5.2 on 2026-07-28 09:41

import django.db.models.deletion
from django.db import migrations, models


def assign_main_branch(apps, schema_editor):
    Branch = apps.get_model("restaurants", "Branch")
    Notification = apps.get_model("reports", "Notification")
    for notification in Notification.objects.filter(
        restaurant__isnull=False,
        branch__isnull=True,
    ):
        branch = Branch.objects.filter(
            restaurant_id=notification.restaurant_id,
            is_main_branch=True,
        ).first()
        if branch:
            Notification.objects.filter(pk=notification.pk).update(branch=branch)


def clear_branch(apps, schema_editor):
    apps.get_model("reports", "Notification").objects.update(branch=None)


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_notification_restaurant'),
        ('restaurants', '0009_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='restaurants.branch'),
        ),
        migrations.RunPython(assign_main_branch, clear_branch),
    ]
