from django.urls import path
from .views import (
    IngredientListCreateView,
    IngredientPaginatedView,
    IngredientRetrieveUpdateDestroyView,
    MenuItemIngredientListCreateView,
    MenuItemIngredientDeleteView,
    StockMovementListView,
    SupplierListCreateView,
    SupplierRetrieveUpdateView,
    stock_transfer_list_create,
    stock_transfer_action,
    inventory_pdf,
    low_stock_items,add_stock_view,adjust_stock_view,
    inventory_dashboard_summary,
    edit_stock_movement_view,
    ingredient_purchase_history_view,
    purchase_invoice_attachment_delete,
    purchase_invoice_attachment_download,
    purchase_invoice_attachment_list_create,
    purchase_invoice_approve,
    purchase_invoice_detail,
    purchase_invoice_list_create,
    search_ingredient_usage_view,
    supplier_ledger_view,
    supplier_payment_detail,
    supplier_payment_list_create,
    supplier_payment_voucher,
    supplier_payment_voucher_pdf,
)


urlpatterns = [
    path('ingredients/', IngredientListCreateView.as_view()),
    path('ingredientsPages/',IngredientPaginatedView.as_view()),
    path('ingredients/<int:pk>/', IngredientRetrieveUpdateDestroyView.as_view()),
    path('ingredients/<int:pk>/purchase-history/', ingredient_purchase_history_view),

    path('recipes/', MenuItemIngredientListCreateView.as_view()),
    path('recipes/<int:pk>/', MenuItemIngredientDeleteView.as_view()),
    path('stock-movements/', StockMovementListView.as_view()),
    path('stock-movements/<int:pk>/edit/', edit_stock_movement_view),
    path('suppliers/', SupplierListCreateView.as_view()),
    path('suppliers/<int:pk>/', SupplierRetrieveUpdateView.as_view()),
    path('suppliers/<int:pk>/ledger/', supplier_ledger_view),
    path('purchase-invoices/', purchase_invoice_list_create),
    path('purchase-invoices/<int:pk>/', purchase_invoice_detail),
    path('purchase-invoices/<int:pk>/approve/', purchase_invoice_approve),
    path('purchase-invoices/<int:pk>/attachments/', purchase_invoice_attachment_list_create),
    path('purchase-invoices/<int:pk>/attachments/<int:attachment_pk>/download/', purchase_invoice_attachment_download),
    path('purchase-invoices/<int:pk>/attachments/<int:attachment_pk>/', purchase_invoice_attachment_delete),
    path('supplier-payments/', supplier_payment_list_create),
    path('supplier-payments/<int:pk>/', supplier_payment_detail),
    path('supplier-payments/<int:pk>/voucher/', supplier_payment_voucher),
    path('supplier-payments/<int:pk>/voucher-pdf/', supplier_payment_voucher_pdf),
    path('stock-transfers/', stock_transfer_list_create),
    path('stock-transfers/<int:pk>/action/', stock_transfer_action),

    path('low-stock/', low_stock_items),
    path('purchases/',add_stock_view),
    path('adjust-stock/', adjust_stock_view),
    path('inventory-summary/',inventory_dashboard_summary),
    path('inventory-pdf/',inventory_pdf),
    path('ingredient-usage/', search_ingredient_usage_view),
]
