# Generated by Django 5.2 on 2026-04-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_delivery_radius_km_restaurant_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='base_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
