# Generated by Django 5.2 on 2026-05-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurant_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='admin_discount_limit',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='manager_discount_limit',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
    ]
