# Generated by Django 5.2 on 2026-06-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurant_admin_discount_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='slogan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
