# Generated by Django 5.2 on 2026-08-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_branch_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='max_branches',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
