# Generated by Django 5.2 on 2026-08-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_menu_qr_public_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchdatamigrationlog',
            name='migration_type',
            field=models.CharField(choices=[('ingredients', 'Ingredients'), ('categories', 'Menu Categories'), ('menu_items', 'Menu Items'), ('platters', 'Platters'), ('modifiers', 'Modifiers'), ('everything', 'Everything')], max_length=30),
        ),
    ]
