# Generated by Django 5.2 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0018_alter_branchdatamigrationlog_migration_type"),
    ]

    operations = [
        # Keep every deployed restaurant visible when the column is introduced.
        migrations.AddField(
            model_name="restaurant",
            name="show_on_landing",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        # Newly created restaurants require an explicit superadmin opt-in.
        migrations.AlterField(
            model_name="restaurant",
            name="show_on_landing",
            field=models.BooleanField(default=False),
        ),
    ]
