# Generated by Django 5.2 on 2026-04-20 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('users', '0013_alter_staff_hire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='Restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='restaurants.restaurant'),
        ),
    ]
