# Generated by Django 5.2 on 2026-04-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_attendance_restaurant_payroll_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='Restaurant',
            new_name='restaurant',
        ),
    ]
